// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {main} from '../models';
import {config} from '../models';

export function AddDataSource(arg1:string,arg2:string,arg3:Record<string, string>):Promise<agent.DataSource>;

export function ApplyOptimizeSuggestions(arg1:string,arg2:Array<main.IndexSuggestion>):Promise<main.OptimizeDataSourceResult>;

export function CancelAnalysis():Promise<void>;

export function CheckRapidBIEnvironmentExists():Promise<boolean>;

export function CheckSessionNameExists(arg1:string,arg2:string):Promise<boolean>;

export function ClearHistory():Promise<void>;

export function CreateChatThread(arg1:string,arg2:string):Promise<main.ChatThread>;

export function CreateRapidBIEnvironment():Promise<string>;

export function DeleteDataSource(arg1:string):Promise<void>;

export function DeleteSessionFile(arg1:string,arg2:string):Promise<void>;

export function DeleteThread(arg1:string):Promise<void>;

export function DiagnosePythonInstallation():Promise<Record<string, any>>;

export function DisableSkill(arg1:string):Promise<void>;

export function EnableSkill(arg1:string):Promise<void>;

export function ExecuteImportAnalysis(arg1:main.AnalysisExport,arg2:string):Promise<void>;

export function ExportAnalysisProcess(arg1:string):Promise<void>;

export function ExportSessionHTML(arg1:string):Promise<void>;

export function ExportToCSV(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ExportToMySQL(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ExportToSQL(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ExtractMetricsFromAnalysis(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExtractSuggestionsFromAnalysis(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveThreadID():Promise<string>;

export function GetAgentMemory(arg1:string):Promise<main.AgentMemoryView>;

export function GetAnalysisPath(arg1:string):Promise<agent.AnalysisPath>;

export function GetChatHistory():Promise<Array<main.ChatThread>>;

export function GetChatHistoryByDataSource(arg1:string):Promise<Array<main.ChatThread>>;

export function GetConfig():Promise<config.Config>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDataSourceTableCount(arg1:string,arg2:string):Promise<number>;

export function GetDataSourceTableData(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetDataSourceTables(arg1:string):Promise<Array<string>>;

export function GetDataSources():Promise<Array<agent.DataSource>>;

export function GetEnabledSkills():Promise<Array<main.SkillInfo>>;

export function GetErrorKnowledgeSummary():Promise<main.ErrorKnowledgeSummary>;

export function GetMySQLDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function GetOptimizeSuggestions(arg1:string):Promise<main.OptimizeSuggestionsResult>;

export function GetPythonEnvironments():Promise<Array<agent.PythonEnvironment>>;

export function GetSessionFilePath(arg1:string,arg2:string):Promise<string>;

export function GetSessionFiles(arg1:string):Promise<Array<main.SessionFile>>;

export function GetSessionRecordings():Promise<Array<agent.AnalysisRecording>>;

export function GetSkillCategories():Promise<Array<string>>;

export function GetSkills():Promise<Array<main.SkillInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ImportAnalysisProcess():Promise<void>;

export function ImportCSVDataSource(arg1:string,arg2:string):Promise<agent.DataSource>;

export function ImportExcelDataSource(arg1:string,arg2:string):Promise<agent.DataSource>;

export function InstallPythonPackages(arg1:string,arg2:Array<string>):Promise<void>;

export function IsCancelRequested():Promise<boolean>;

export function LoadMetricsJson(arg1:string):Promise<string>;

export function Log(arg1:string):Promise<void>;

export function MarkAsFinding(arg1:string,arg2:string,arg3:number):Promise<void>;

export function OpenDevTools():Promise<void>;

export function OpenSessionFile(arg1:string,arg2:string):Promise<void>;

export function OpenSessionResultsDirectory(arg1:string):Promise<void>;

export function PrepareImportAnalysis():Promise<main.AnalysisExport>;

export function ReadChartDataFile(arg1:string,arg2:string):Promise<string>;

export function ReloadSkills():Promise<void>;

export function ReplayAnalysisRecording(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<agent.ReplayResult>;

export function SaveChatHistory(arg1:Array<main.ChatThread>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveMetricsJson(arg1:string,arg2:string):Promise<void>;

export function SaveSessionRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectCSVFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectExcelFile():Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetChatOpen(arg1:boolean):Promise<void>;

export function ShowMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestLLMConnection(arg1:config.Config):Promise<main.ConnectionResult>;

export function TestMySQLConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMySQLExportConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateThreadTitle(arg1:string,arg2:string):Promise<string>;

export function UpdateWorkingContext(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ValidateImportAnalysis(arg1:main.AnalysisExport,arg2:string):Promise<main.ValidationResult>;

export function ValidatePython(arg1:string):Promise<agent.PythonValidationResult>;

export function WriteSystemLog(arg1:string,arg2:string,arg3:string):Promise<void>;
