// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDataSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDataSource'](arg1, arg2, arg3);
}

export function ApplyOptimizeSuggestions(arg1, arg2) {
  return window['go']['main']['App']['ApplyOptimizeSuggestions'](arg1, arg2);
}

export function CanStartNewAnalysis() {
  return window['go']['main']['App']['CanStartNewAnalysis']();
}

export function CancelAnalysis() {
  return window['go']['main']['App']['CancelAnalysis']();
}

export function CheckComponentHasData(arg1, arg2) {
  return window['go']['main']['App']['CheckComponentHasData'](arg1, arg2);
}

export function CheckRapidBIEnvironmentExists() {
  return window['go']['main']['App']['CheckRapidBIEnvironmentExists']();
}

export function CheckSessionNameExists(arg1, arg2) {
  return window['go']['main']['App']['CheckSessionNameExists'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateChatThread(arg1, arg2) {
  return window['go']['main']['App']['CreateChatThread'](arg1, arg2);
}

export function CreateRapidBIEnvironment() {
  return window['go']['main']['App']['CreateRapidBIEnvironment']();
}

export function DeleteDataSource(arg1) {
  return window['go']['main']['App']['DeleteDataSource'](arg1);
}

export function DeleteSessionFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteSessionFile'](arg1, arg2);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteTable(arg1, arg2) {
  return window['go']['main']['App']['DeleteTable'](arg1, arg2);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function DiagnosePythonInstallation() {
  return window['go']['main']['App']['DiagnosePythonInstallation']();
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function DownloadSessionFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadSessionFile'](arg1, arg2);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function ExecuteImportAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ExecuteImportAnalysis'](arg1, arg2);
}

export function ExportAnalysisProcess(arg1) {
  return window['go']['main']['App']['ExportAnalysisProcess'](arg1);
}

export function ExportDashboard(arg1) {
  return window['go']['main']['App']['ExportDashboard'](arg1);
}

export function ExportDashboardToExcel(arg1) {
  return window['go']['main']['App']['ExportDashboardToExcel'](arg1);
}

export function ExportDashboardToPDF(arg1) {
  return window['go']['main']['App']['ExportDashboardToPDF'](arg1);
}

export function ExportDashboardToPPT(arg1) {
  return window['go']['main']['App']['ExportDashboardToPPT'](arg1);
}

export function ExportSessionFilesToZip(arg1, arg2) {
  return window['go']['main']['App']['ExportSessionFilesToZip'](arg1, arg2);
}

export function ExportSessionHTML(arg1) {
  return window['go']['main']['App']['ExportSessionHTML'](arg1);
}

export function ExportTableToExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportTableToExcel'](arg1, arg2);
}

export function ExportToCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToCSV'](arg1, arg2, arg3);
}

export function ExportToJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToJSON'](arg1, arg2, arg3);
}

export function ExportToMySQL(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExportToMySQL'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportToSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToSQL'](arg1, arg2, arg3);
}

export function ExtractMetricsFromAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractMetricsFromAnalysis'](arg1, arg2, arg3);
}

export function ExtractSuggestionsFromAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractSuggestionsFromAnalysis'](arg1, arg2, arg3);
}

export function GenerateCSVThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GenerateCSVThumbnail'](arg1, arg2);
}

export function GenerateIntentSuggestions(arg1, arg2) {
  return window['go']['main']['App']['GenerateIntentSuggestions'](arg1, arg2);
}

export function GenerateIntentSuggestionsWithExclusions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateIntentSuggestionsWithExclusions'](arg1, arg2, arg3);
}

export function GetActiveAnalysisCount() {
  return window['go']['main']['App']['GetActiveAnalysisCount']();
}

export function GetActiveThreadID() {
  return window['go']['main']['App']['GetActiveThreadID']();
}

export function GetAgentMemory(arg1) {
  return window['go']['main']['App']['GetAgentMemory'](arg1);
}

export function GetAnalysisPath(arg1) {
  return window['go']['main']['App']['GetAnalysisPath'](arg1);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetChatHistoryByDataSource(arg1) {
  return window['go']['main']['App']['GetChatHistoryByDataSource'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDataSourceTableCount(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceTableCount'](arg1, arg2);
}

export function GetDataSourceTableData(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceTableData'](arg1, arg2);
}

export function GetDataSourceTables(arg1) {
  return window['go']['main']['App']['GetDataSourceTables'](arg1);
}

export function GetDataSources() {
  return window['go']['main']['App']['GetDataSources']();
}

export function GetEnabledSkills() {
  return window['go']['main']['App']['GetEnabledSkills']();
}

export function GetErrorKnowledgeSummary() {
  return window['go']['main']['App']['GetErrorKnowledgeSummary']();
}

export function GetFilesByCategory(arg1) {
  return window['go']['main']['App']['GetFilesByCategory'](arg1);
}

export function GetMySQLDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMySQLDatabases'](arg1, arg2, arg3, arg4);
}

export function GetOptimizeSuggestions(arg1) {
  return window['go']['main']['App']['GetOptimizeSuggestions'](arg1);
}

export function GetPythonEnvironments() {
  return window['go']['main']['App']['GetPythonEnvironments']();
}

export function GetSessionFileAsBase64(arg1, arg2) {
  return window['go']['main']['App']['GetSessionFileAsBase64'](arg1, arg2);
}

export function GetSessionFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetSessionFilePath'](arg1, arg2);
}

export function GetSessionFiles(arg1) {
  return window['go']['main']['App']['GetSessionFiles'](arg1);
}

export function GetSessionRecordings() {
  return window['go']['main']['App']['GetSessionRecordings']();
}

export function GetSkillCategories() {
  return window['go']['main']['App']['GetSkillCategories']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportAnalysisProcess() {
  return window['go']['main']['App']['ImportAnalysisProcess']();
}

export function ImportCSVDataSource(arg1, arg2) {
  return window['go']['main']['App']['ImportCSVDataSource'](arg1, arg2);
}

export function ImportExcelDataSource(arg1, arg2) {
  return window['go']['main']['App']['ImportExcelDataSource'](arg1, arg2);
}

export function ImportJSONDataSource(arg1, arg2) {
  return window['go']['main']['App']['ImportJSONDataSource'](arg1, arg2);
}

export function InstallPythonPackages(arg1, arg2) {
  return window['go']['main']['App']['InstallPythonPackages'](arg1, arg2);
}

export function InstallSkillsFromZip() {
  return window['go']['main']['App']['InstallSkillsFromZip']();
}

export function IsCancelRequested() {
  return window['go']['main']['App']['IsCancelRequested']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LoadLayout(arg1) {
  return window['go']['main']['App']['LoadLayout'](arg1);
}

export function LoadMetricsJson(arg1) {
  return window['go']['main']['App']['LoadMetricsJson'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function MarkAsFinding(arg1, arg2, arg3) {
  return window['go']['main']['App']['MarkAsFinding'](arg1, arg2, arg3);
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function OpenSessionFile(arg1, arg2) {
  return window['go']['main']['App']['OpenSessionFile'](arg1, arg2);
}

export function OpenSessionResultsDirectory(arg1) {
  return window['go']['main']['App']['OpenSessionResultsDirectory'](arg1);
}

export function PrepareImportAnalysis() {
  return window['go']['main']['App']['PrepareImportAnalysis']();
}

export function ReadChartDataFile(arg1, arg2) {
  return window['go']['main']['App']['ReadChartDataFile'](arg1, arg2);
}

export function ReloadSkills() {
  return window['go']['main']['App']['ReloadSkills']();
}

export function RenameColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameColumn'](arg1, arg2, arg3, arg4);
}

export function RenameDataSource(arg1, arg2) {
  return window['go']['main']['App']['RenameDataSource'](arg1, arg2);
}

export function ReplayAnalysisRecording(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplayAnalysisRecording'](arg1, arg2, arg3, arg4);
}

export function SaveChatHistory(arg1) {
  return window['go']['main']['App']['SaveChatHistory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function SaveMetricsJson(arg1, arg2) {
  return window['go']['main']['App']['SaveMetricsJson'](arg1, arg2);
}

export function SaveSessionRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionRecording'](arg1, arg2, arg3);
}

export function SelectCSVFile() {
  return window['go']['main']['App']['SelectCSVFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectJSONFile() {
  return window['go']['main']['App']['SelectJSONFile']();
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function SemanticOptimizeDataSource(arg1) {
  return window['go']['main']['App']['SemanticOptimizeDataSource'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetChatOpen(arg1) {
  return window['go']['main']['App']['SetChatOpen'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function ShowMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2, arg3);
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}

export function TestMCPService(arg1) {
  return window['go']['main']['App']['TestMCPService'](arg1);
}

export function TestMySQLConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMySQLConnection'](arg1, arg2, arg3, arg4);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function TestSearchAPI(arg1) {
  return window['go']['main']['App']['TestSearchAPI'](arg1);
}

export function TestSearchEngine(arg1) {
  return window['go']['main']['App']['TestSearchEngine'](arg1);
}

export function TestSearchTools(arg1) {
  return window['go']['main']['App']['TestSearchTools'](arg1);
}

export function TestUAPIConnection(arg1, arg2) {
  return window['go']['main']['App']['TestUAPIConnection'](arg1, arg2);
}

export function UpdateMySQLExportConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMySQLExportConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateThreadTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateThreadTitle'](arg1, arg2);
}

export function UpdateWorkingContext(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkingContext'](arg1, arg2);
}

export function ValidateImportAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ValidateImportAnalysis'](arg1, arg2);
}

export function ValidatePython(arg1) {
  return window['go']['main']['App']['ValidatePython'](arg1);
}

export function WriteSystemLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteSystemLog'](arg1, arg2, arg3);
}
