// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {main} from '../models';
import {config} from '../models';

export function AddDataSource(arg1:string,arg2:string,arg3:Record<string, string>):Promise<agent.DataSource>;

export function AssetizeSession(arg1:string):Promise<void>;

export function CheckSessionNameExists(arg1:string,arg2:string):Promise<boolean>;

export function ClearHistory():Promise<void>;

export function CreateChatThread(arg1:string,arg2:string):Promise<main.ChatThread>;

export function DeleteDataSource(arg1:string):Promise<void>;

export function DeleteThread(arg1:string):Promise<void>;

export function ExportSessionHTML(arg1:string):Promise<void>;

export function ExportToCSV(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ExportToMySQL(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ExportToSQL(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function GetAgentMemory(arg1:string):Promise<main.AgentMemoryView>;

export function GetChatHistory():Promise<Array<main.ChatThread>>;

export function GetChatHistoryByDataSource(arg1:string):Promise<Array<main.ChatThread>>;

export function GetConfig():Promise<config.Config>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDataSourceTableCount(arg1:string,arg2:string):Promise<number>;

export function GetDataSourceTableData(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetDataSourceTables(arg1:string):Promise<Array<string>>;

export function GetDataSources():Promise<Array<agent.DataSource>>;

export function GetMySQLDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function GetPythonEnvironments():Promise<Array<agent.PythonEnvironment>>;

export function Greet(arg1:string):Promise<string>;

export function ImportCSVDataSource(arg1:string,arg2:string):Promise<agent.DataSource>;

export function ImportExcelDataSource(arg1:string,arg2:string):Promise<agent.DataSource>;

export function Log(arg1:string):Promise<void>;

export function ReplayAnalysis():Promise<void>;

export function SaveChatHistory(arg1:Array<main.ChatThread>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectCSVFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectExcelFile():Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SetChatOpen(arg1:boolean):Promise<void>;

export function ShowMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestLLMConnection(arg1:config.Config):Promise<main.ConnectionResult>;

export function TestMySQLConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMySQLExportConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateThreadTitle(arg1:string,arg2:string):Promise<string>;

export function ValidatePython(arg1:string):Promise<agent.PythonValidationResult>;
