// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetPythonEnvironments() {
  return window['go']['main']['App']['GetPythonEnvironments']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveChatHistory(arg1) {
  return window['go']['main']['App']['SaveChatHistory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  window['go']['main']['App']['SelectDirectory']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}

export function ValidatePython(arg1) {
  return window['go']['main']['App']['ValidatePython'](arg1);
}