// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDataSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDataSource'](arg1, arg2, arg3);
}

export function AssetizeSession(arg1) {
  return window['go']['main']['App']['AssetizeSession'](arg1);
}

export function CancelAnalysis() {
  return window['go']['main']['App']['CancelAnalysis']();
}

export function CheckSessionNameExists(arg1, arg2) {
  return window['go']['main']['App']['CheckSessionNameExists'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateChatThread(arg1, arg2) {
  return window['go']['main']['App']['CreateChatThread'](arg1, arg2);
}

export function DeleteDataSource(arg1) {
  return window['go']['main']['App']['DeleteDataSource'](arg1);
}

export function DeleteSessionFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteSessionFile'](arg1, arg2);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function ExportSessionHTML(arg1) {
  return window['go']['main']['App']['ExportSessionHTML'](arg1);
}

export function ExportToCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToCSV'](arg1, arg2, arg3);
}

export function ExportToMySQL(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExportToMySQL'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportToSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToSQL'](arg1, arg2, arg3);
}

export function ExtractMetricsFromAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ExtractMetricsFromAnalysis'](arg1, arg2);
}

export function GetActiveThreadID() {
  return window['go']['main']['App']['GetActiveThreadID']();
}

export function GetAgentMemory(arg1) {
  return window['go']['main']['App']['GetAgentMemory'](arg1);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetChatHistoryByDataSource(arg1) {
  return window['go']['main']['App']['GetChatHistoryByDataSource'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDataSourceTableCount(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceTableCount'](arg1, arg2);
}

export function GetDataSourceTableData(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceTableData'](arg1, arg2);
}

export function GetDataSourceTables(arg1) {
  return window['go']['main']['App']['GetDataSourceTables'](arg1);
}

export function GetDataSources() {
  return window['go']['main']['App']['GetDataSources']();
}

export function GetEnabledSkills() {
  return window['go']['main']['App']['GetEnabledSkills']();
}

export function GetErrorKnowledgeSummary() {
  return window['go']['main']['App']['GetErrorKnowledgeSummary']();
}

export function GetMySQLDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMySQLDatabases'](arg1, arg2, arg3, arg4);
}

export function GetPythonEnvironments() {
  return window['go']['main']['App']['GetPythonEnvironments']();
}

export function GetSessionFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetSessionFilePath'](arg1, arg2);
}

export function GetSessionFiles(arg1) {
  return window['go']['main']['App']['GetSessionFiles'](arg1);
}

export function GetSessionRecordings() {
  return window['go']['main']['App']['GetSessionRecordings']();
}

export function GetSkillCategories() {
  return window['go']['main']['App']['GetSkillCategories']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportCSVDataSource(arg1, arg2) {
  return window['go']['main']['App']['ImportCSVDataSource'](arg1, arg2);
}

export function ImportExcelDataSource(arg1, arg2) {
  return window['go']['main']['App']['ImportExcelDataSource'](arg1, arg2);
}

export function IsCancelRequested() {
  return window['go']['main']['App']['IsCancelRequested']();
}

export function LoadMetricsJson(arg1) {
  return window['go']['main']['App']['LoadMetricsJson'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function OpenSessionFile(arg1, arg2) {
  return window['go']['main']['App']['OpenSessionFile'](arg1, arg2);
}

export function OpenSessionResultsDirectory(arg1) {
  return window['go']['main']['App']['OpenSessionResultsDirectory'](arg1);
}

export function ReloadSkills() {
  return window['go']['main']['App']['ReloadSkills']();
}

export function ReplayAnalysis() {
  return window['go']['main']['App']['ReplayAnalysis']();
}

export function ReplayAnalysisRecording(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplayAnalysisRecording'](arg1, arg2, arg3, arg4);
}

export function SaveChatHistory(arg1) {
  return window['go']['main']['App']['SaveChatHistory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveMetricsJson(arg1, arg2) {
  return window['go']['main']['App']['SaveMetricsJson'](arg1, arg2);
}

export function SaveSessionRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionRecording'](arg1, arg2, arg3);
}

export function SelectCSVFile() {
  return window['go']['main']['App']['SelectCSVFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetChatOpen(arg1) {
  return window['go']['main']['App']['SetChatOpen'](arg1);
}

export function ShowMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2, arg3);
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}

export function TestMySQLConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMySQLConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateMySQLExportConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMySQLExportConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateThreadTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateThreadTitle'](arg1, arg2);
}

export function ValidatePython(arg1) {
  return window['go']['main']['App']['ValidatePython'](arg1);
}
