// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteThread(arg1:string):Promise<void>;

export function GetChatHistory():Promise<main.ChatThread[]>;

export function GetConfig():Promise<main.Config>;

export function GetDashboardData():Promise<main.DashboardData>;

export function Greet(arg1:string):Promise<string>;

export function SaveChatHistory(arg1:main.ChatThread[]):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function TestLLMConnection(arg1:main.Config):Promise<main.ConnectionResult>;